version: '3.8'

volumes:
  data:
services:
  db:
    build: ./db
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - api
  api:
    build: ./api
    environment:
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD=example
      - DB_DATABASE=mydb
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - db